### ISSUE TITLE
Enable Debug Logging

### ISSUE THREAD

**Issue by MarkEnverus** [apache/casbin-server#100]
I am trying to spin up a docker with the postgres example here: https://github.com/casbin/casbin-server/blob/master/config/connection_config_psql_example.json
Is there a way to enable Debug logging as the server seems to spin up but anytime I make a call to the API I get "missing enforcer" which leads me to believe that the config file isn't loaded properly.
Logs don't show anything by default so wasn't sure if there was a config or ENV variable for Debug logging?

**Comment by hsluoyz** [comment]
@MarkEnverus can you make a PR to support it?

**Comment by MarkEnverus** [comment]
I pulled the code down but the docker file won't build for testing:
16.65 # google.golang.org/grpc/internal/buffer
16.65 ../pkg/mod/google.golang.org/grpc@v1.58.2/internal/buffer/unbounded.go:37:15: undefined: any
16.65 ../pkg/mod/google.golang.org/grpc@v1.58.2/internal/buffer/unbounded.go:40:12: undefined: any
16.65 ../pkg/mod/google.golang.org/grpc@v1.58.2/internal/buffer/unbounded.go:45:33: undefined: any
16.65 ../pkg/mod/google.golang.org/grpc@v1.58.2/internal/buffer/unbounded.go:49:27: undefined: any
16.65 ../pkg/mod/google.golang.org/grpc@v1.58.2/internal/buffer/unbounded.go:92:34: undefined: any
16.65 note: module requires Go 1.19

If you update Go, other modules fail?

**Comment by MarkEnverus** [comment]
I was able to fix the Docker issue (we need to pin to specific go versions) and I found the issue causing the confusion above. 

Right now even when a config file is passed (with an enforcer say in a Docker Compose or Docker) - they are not used unless an "Empty" NewAdapter and NewEnforcer is passed.  Is this the intended logic?  I would think if a config file is passed it should be read on start up?

**Comment by MarkEnverus** [comment]
@hsluoyz i tried to open a PR but i can't commit to a branch?

**Comment by hsluoyz** [comment]
@MarkEnverus https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by MarkEnverus** [comment]
@hsluoyz  i know how to open a PR - i cannot due to not having access to this repo - if you give me access or make it public i can make a PR - but when i try to create the PR in the GUI or command line i cannot...


remote: Permission to casbin/casbin-server.git denied to MarkEnverus.
fatal: unable to access 'https://github.com/casbin/casbin-server.git/': The requested URL returned error: 403
