### ISSUE TITLE
server is not distributed

### ISSUE THREAD

**Issue by Danny5487401** [apache/casbin-server#109]
![image](https://github.com/casbin/casbin-server/assets/64348131/9bc67c48-c7a8-4e39-8f5d-5d9fc54dd672)

it will be wrong to have 2 server and client will find wrong server by using handler number

**Comment by hsluoyz** [comment]
@Danny5487401 each server has its own `enforcerMap`

**Comment by Danny5487401** [comment]
@hsluoyz it helps me with watchers using https://casbin.org/docs/watchers/. And it will work by using NewDistributedEnforcer(params ...interface{})

**Comment by Danny5487401** [comment]
> @Danny5487401 each server has its own `enforcerMap`

@hsluoyz  pls rethink about it. The grpc client will ramdom choose one of two server. while client one use handler 2 and server one have enforcerMap up to 1 ,server one have enforcerMap up to 2 , client one may try to connect server one

**Comment by dev-demor** [comment]
@Danny5487401 I have encountered the same problem, which has not been officially resolved yet. Do you already have a strategy to solve it?
