### ISSUE TITLE
Casbin-server with ABAC

### ISSUE THREAD

**Issue by anton-khodak** [apache/casbin-server#11]
Hi, 

I would like to ask about how to use Casbin Server with ABAC. If I understand correctly, I need to serialize a Go structure to protobuf and send it to the `enforce` function, but looking at the code I can't clearly understand whether I can pass a structure (not a string) as a subject/object. 

In other words, is something like https://github.com/casbin/casbin/blob/master/model_test.go#L307-L312 possible with casbin-server?

**Comment by hsluoyz** [comment]
Currently Casbin Server doesn't support to pass Go structs as parameters of ``Enforce()``. As you can see, the protobuf is defined as ``repeated string``. I don't know whether protobuf supports custom structs? If protobuf doesn't support it, we can do nothing about it then.

https://github.com/casbin/casbin-server/blob/2dcdc6a34b308b16c75bbbc0dbbedbd5c2ae36a6/proto/casbin.proto#L89-L92

**Comment by hsluoyz** [comment]
@nodece @Chalin-Shi @BetaCat0 

I think we need to support ABAC on Casbin Server to. Do you have any ideas on how to implement it on grpc?

**Comment by BetaCat0** [comment]
@hsluoyz I think it depends on whether protobuf supports custom structs. If not, we have to pick some flexible carriers of data such as a JSON string. However this will bring additional overhead when processing them and do harm to performance. Any good ideas?

**Comment by hsluoyz** [comment]
After walking through the data types in ProtoBuf: https://developers.google.com/protocol-buffers/docs/proto3, I think we have to use the JSON way. So Casbin-Server's client will accept a Go struct, encode it into a JSON string, then pass it to Casbin-Server via gRPC. The Casbin-Server will decode it to Go struct and pass it to Casbin.

This naturally works for Casbin-Server's Go client. I don't know how other languages like Java handle the encoding of a Java class instance. We may need to take care of that when we have other languages' clients.

**Comment by anton-khodak** [comment]
@hsluoyz I am willing to start using ABAC with casbin-server as soon as possible, so I can contribute to this feature. Have you already started working on this (so that we don't duplicate efforts)?

**Comment by hsluoyz** [comment]
@anton-khodak thanks. We have a PR here: https://github.com/casbin/casbin-server/pull/13. I haven't start to review it yet. Can you help me review it, and check if this is what you want?

**Comment by hsluoyz** [comment]
The PR: https://github.com/casbin/casbin-server/pull/13 has been merged, closed.
