### ISSUE TITLE
enforcer EnableAcceptJsonRequest

### ISSUE THREAD

**Issue by Danny5487401** [apache/casbin-server#111]
how to turn  EnableAcceptJsonRequest for casbin-client

**Comment by hsluoyz** [comment]
@Danny5487401 what do you mean?

**Comment by Danny5487401** [comment]
@hsluoyz  use grpc to EnableAcceptJsonRequest

```go

func (e *Enforcer) EnableAcceptJsonRequest(acceptJsonRequest bool) {
  e.acceptJsonRequest = acceptJsonRequest
}

```

**Comment by hsluoyz** [comment]
@Danny5487401 @ali-shokoohi can you make a PR?

**Comment by ali-shokoohi** [comment]
Okay @hsluoyz . I'm going to work on it
