### ISSUE TITLE
[bug] fix the CI dockerhub release error

### ISSUE THREAD

**Issue by hsluoyz** [apache/casbin-server#117]
See: https://github.com/casbin/casbin-server/actions/runs/11123579881/job/30907360372

![image](https://github.com/user-attachments/assets/443f9ee4-9baf-4bec-acab-f96ae993c805)

**Comment by ali-shokoohi** [comment]
@hsluoyz Hi. Because this project is using Golang version 1.19, We should choose good versions for packages.
Also, we have "google.golang.org/grpc" in the go.mod file, we only need to run `go mod download` command.
I just created a bugfix PR here:
https://github.com/casbin/casbin-server/pull/118
