### ISSUE TITLE
Request for Linux/x86_64 Support for Casbin-Server Docker Image

### ISSUE THREAD

**Issue by yuuyayukinanana** [apache/casbin-server#120]
Currently, the official Docker image for Casbin-Server is only provided for the linux/amd64 architecture. However, the linux/x86_64 architecture is more widely used and would greatly benefit a larger number of users.

We would greatly appreciate it if you could consider providing an official Docker image for the linux/x86_64 architecture. 

casbin/casbin-server Tags | Docker Hub
https://hub.docker.com/r/casbin/casbin-server/tags

**Comment by hsluoyz** [comment]
@yuuyayukinanana bro, I think amd64 and x86_64 are the same thing???

**Comment by yuuyayukinanana** [comment]
@hsluoyz 
Thank you for your comment.

While we don't see a significant difference between linux/amd64 and linux/x86_64, we need linux/x86_64 support to run Casbin-Server on AWS Fargate, as linux/amd64 is not supported in that environment.

It would be greatly appreciated if you could provide official support for linux/x86_64. Thank you for considering this request!

Amazon ECS task definition differences for the Fargate launch type - Amazon Elastic Container Service
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-tasks-services.html
```
Tasks that run on X86_64 or ARM64 CPU architecture are supported.
```

**Comment by hsluoyz** [comment]
As I already said, amd64 and x86_64 are the same thing. Closed here

**Comment by yuuyayukinanana** [comment]
Thank you for your comment.
I tried to implement it and it was the same.
Sorry for the trouble.
