### ISSUE TITLE
Set up casbin-server Docker image on Dockerhub

### ISSUE THREAD

**Issue by anton-khodak** [apache/casbin-server#16]
- [x] push image to DockerHub
- [x] set up a hook for building an image for each new push to master

**Comment by hsluoyz** [comment]
Hi @anton-khodak , I have built Casbin's organization account on DockerHub here: https://hub.docker.com/r/casbin/casbin/. Would you like act as a contributor and push the images? If it's OK, I will add you as a collaborator.

**Comment by anton-khodak** [comment]
yes, please!

**Comment by hsluoyz** [comment]
OK. What's your username or Email in DockerHub?

**Comment by anton-khodak** [comment]
@hsluoyz "khodak"

**Comment by hsluoyz** [comment]
Added :)

**Comment by anton-khodak** [comment]
can you also add me to the casbin organisation as a member? DockerHub will request access to repositories for setting up an automatic build

**Comment by hsluoyz** [comment]
Added to the owners team :)

**Comment by anton-khodak** [comment]
Looks like I'm still not in: https://github.com/orgs/casbin/people

**Comment by hsluoyz** [comment]
Oh, you mean the Github organization? Already added.

**Comment by anton-khodak** [comment]
The Docker image is available at https://hub.docker.com/r/casbin/casbin-server, builds trigger at every push to master

**Comment by hsluoyz** [comment]
Thanks for the contribution!
