### ISSUE TITLE
Lowercase for first character of ABAC attributes

### ISSUE THREAD

**Issue by rlouedec** [apache/casbin-server#20]
Hi,

I am wondering if having a first capital character for ABAC attributes is a Casbin requirement because I didn't see it mentioned anywhere and it caused me trouble when I was trying to understand my problem.

https://github.com/casbin/casbin-server/blob/bbee114897632689c78071c5542db2baceae50b9/server/abac.go#L68

**Comment by hsluoyz** [comment]
Hi @RLouedec , thanks for the report. It has been documented in: https://github.com/casbin/casbin-server/commit/23ee7347ddbc0b9f5113ad26b3757d6da843428f
