### ISSUE TITLE
Lock enforcers 

### ISSUE THREAD

**Issue by mrfeathers** [apache/casbin-server#21]
> I've notices some strange behavior using ABAC. For example, I have a resource with two attributes "id" and "status". I print attrList in logs and when I see log like this "{verified 1 map[Id:V1 Status:V0]}" the result is right, but when it's "{verified 1 map[Status:V0, Id:V1 ]}" - the result is wrong. Mapping still seems correct, but the result is wrong
I create one adapter and one enforcer, that are saved in maps in server/enforcer.go, than I make several enforce requests with ABAC resource. Resource is parsed to attribute list and the enforcer model is also changes (e.x. resource attrList is like {1 verified} [Id:V0, Status:V1], model matcher changes to "m = g(r_sub, r_resource.V0) && r_resource.V1 != 'unverified' ") and due to golang random iteration attrList can be different each time. And the enforcer and its model are the shared resource between several enforce requests, so even though the resource mapping seems correct, the result is wrong sometimes because the model can be changed by another request before current request is done.

Probably enforcers must be locked, so different requests won't change it's model value concurrently

**Comment by nodece** [comment]
@mrfeathers Thank you for your report! Please try the latest version.
