### ISSUE TITLE
What does this mean: "Casbin-Server is designed to be compute-intensive (for calculating whether an access should be allowed) instead of a centralized policy storage."

### ISSUE THREAD

**Issue by chmorgan** [apache/casbin-server#27]
I looked through the code and don't see any compute intensive operations designed to result in a computation expense for each policy access.

Also, isn't this a central policy storage as its a Casbin-server that could be used by a backend to enforce access policies? Or am I misunderstanding the project?

Backstory is that I'd like to add Casbin support to my backend restful api. I think I have a model I can understand and I'm able to insert that into my restful framework (go-swagger generated) but I'm looking at whether I should create another docker container just for Casbin and use casbin-server, and if I can then easily plug in the casbin/web-ui to this Casbin server to provide a way to debug policies. The backend will of course manage some of that itself, for example creating policies when users add new devices for example, but of course maintenance access is required to see what is going on there.

**Comment by hsluoyz** [comment]
The ``Enforce()`` call is expensive and is running inside Casbin-Server. The centralized policy storage can be the same server or another server than Casbin-Server, which is determined by the adapter's config.

**Comment by chmorgan** [comment]
Would it make sense to rewrite that sentence to say something like:

“The enforce request to the Casbin-server is compute intensive as it is retrieving and checking against policies. The policies can be stored locally or in a database.”

Replacing:

"Casbin-Server is designed to be compute-intensive (for calculating whether an access should be allowed) instead of a centralized policy storage."

I can submit a pull request if so.

**Comment by hsluoyz** [comment]
Sure. Please send a PR.

**Comment by chmorgan** [comment]
Pr merged, closing
