### ISSUE TITLE
mutil application with casbin-server

### ISSUE THREAD

**Issue by UOvOU** [apache/casbin-server#36]
if i have many application on the k8s
every application has their own  casbin-server  or  all applications have  only one common  casbin-server ??

**Comment by hsluoyz** [comment]
One is enough. One Casbin-server can host multiple Casbin enforcers. One enforcer handles authorization requests from one app.

**Comment by UOvOU** [comment]
> One is enough. One Casbin-server can host multiple Casbin enforcers. One enforcer handles authorization requests from one app.

thanks !

**Comment by UOvOU** [comment]
> > One is enough. One Casbin-server can host multiple Casbin enforcers. One enforcer handles authorization requests from one app.
> 
> thanks !



> One is enough. One Casbin-server can host multiple Casbin enforcers. One enforcer handles authorization requests from one app.

I am new to casbin,  I just read all doc yesterday but  I still have one question 
If one application, have mutil kind user table  how can I get the specific table rbac roles list
example table:  admin,  user 

maybe is add table_name as doman ??
