### ISSUE TITLE
This project is life ?

### ISSUE THREAD

**Issue by GustavoAmerico** [apache/casbin-server#38]
I'm creating the issue for extend the life cycle for this project. 
1. Has a team working ?
1. Is safe implement the solution ? 
1. The GoLang and dependencies are constant updated?

**Comment by hsluoyz** [comment]
Yes. This project is still alive. If you encounter any issues, please raise it.

We also have some developers working on Casbin dashboard right now: https://github.com/casbin/casbin-dashboard . It provides a UI to manage policies. They can integrate together.

**Comment by hsluoyz** [comment]
@nodece @00LT00 @dovics @BetaCat0 can anyone work on this?

**Comment by hsluoyz** [comment]
@00LT00

**Comment by 00LT00** [comment]
I have set the Notifications to follow this repo, I will see the new issue and so on.

**Comment by hsluoyz** [comment]
Closed as resolved.
