### ISSUE TITLE
About HTTP interface

### ISSUE THREAD

**Issue by andyyumiao** [apache/casbin-server#42]
Some of my questions are：
1.How can I update the policy through the HTTP interface?
2.How to update model through HTTP interface?
3.Where is the API for verifying permissions(I mean HTTP interface)?
4.Do I need to implement it myself, or if there are detailed HTTP interface documents, can you provide them?

**Comment by hsluoyz** [comment]
Closed as not being specific.

**Comment by hsluoyz** [comment]
@andyyumiao as our README said, Casbin-Server exposes gRPC API to clients. So there's no HTTP or RESTful API for it currently.
