### ISSUE TITLE
The support for Casbin Management & RBAC APIs is not most up to date

### ISSUE THREAD

**Issue by send2vinnie** [apache/casbin-server#43]
The support for Casbin Management & RBAC APIs is not most up to date by comparing the numbers of the APIs seen in the official document and the protobuf file.

**Comment by hsluoyz** [comment]
@send2vinnie which APIs do you desire most?

**Comment by send2vinnie** [comment]
I am seeking the alternative of Casbin.net once we find some obstacle while using it and I found Casbin-Server is a good option if it supports all the APIs.

**Comment by hsluoyz** [comment]
@send2vinnie can you list some missing APIs that you want most for now? We have intention to improve the API coverage but it cannot be done in one day. So we have to choose some APIs to implement first. Your input will be valuable!
