### ISSUE TITLE
Fix docker badge

### ISSUE THREAD

**Issue by hsluoyz** [apache/casbin-server#46]
![image](https://user-images.githubusercontent.com/3787410/125157414-6a08aa80-e19d-11eb-88e0-e8b92d76737e.png)

**Comment by hsluoyz** [comment]
@closetool

**Comment by kilosonc** [comment]
@hsluoyz I tried, but the badge shows failing  https://img.shields.io/docker/cloud/build/casbin/casbin-server. So I asked in shields repo https://github.com/badges/shields/discussions/6754, but been told it is docker hub's fault.
So I ask for triggering a building to see what happens.

**Comment by hsluoyz** [comment]
@closetool plz trigger a build

**Comment by kilosonc** [comment]
@hsluoyz Perhaps I could not, cause I don't have casbin's docker hub account.

**Comment by hsluoyz** [comment]
@closetool I have added you to the org: https://hub.docker.com/orgs/casbin

![image](https://user-images.githubusercontent.com/3787410/125277189-b4c42700-e343-11eb-8726-715c7524c7c5.png)

**Comment by kilosonc** [comment]
@hsluoyz Build failed
```
closetool@Ubuntu-20:~/tasks/casbin-server$ docker build .
Sending build context to Docker daemon  471.6kB
Step 1/13 : FROM golang:1.12
 ---> ffcaee6f7d8b
Step 2/13 : RUN apt-get update &&     apt-get -y install git unzip build-essential autoconf libtool
 ---> Using cache
 ---> 99b7a5384050
Step 3/13 : RUN git clone https://github.com/google/protobuf.git &&     cd protobuf &&     ./autogen.sh &&     ./configure &&     make &&     make install &&     ldconfig &&     make clean &&     cd .. &&     rm -r protobuf
 ---> Using cache
 ---> 2d1656e84736
Step 4/13 : RUN go get google.golang.org/grpc
 ---> Running in e01e74df6df4
# golang.org/x/net/http2
src/golang.org/x/net/http2/client_conn_pool.go:305:6: undefined: errors.Is
The command '/bin/sh -c go get google.golang.org/grpc' returned a non-zero code: 2
```

**Comment by hsluoyz** [comment]
@closetool then plz fix it
