### ISSUE TITLE
bug: some methods do not return an error

### ISSUE THREAD

**Issue by Angry-Chick** [apache/casbin-server#48]
https://github.com/casbin/casbin-server/blob/759993b8ac7e9cc70d22e485d09e8f2dd5b3444e/server/rbac_api.go#L42
https://github.com/casbin/casbin-server/blob/759993b8ac7e9cc70d22e485d09e8f2dd5b3444e/server/rbac_api.go#L202
As shown in the connection，an error should be returned

**Comment by 00LT00** [comment]
plz fix DCO @Angry-Chick
