### ISSUE TITLE
Environment variable for connection_config.json path

### ISSUE THREAD

**Issue by svetha-cvl** [apache/casbin-server#51]
The path for config/connection_config.json is currently hardcoded in server/enforcer.go and server/adapter.go. Proposing an enhancement to read the connection_config.json location from an environment variable for ease of deployments. We can fall back to the existing config/connection_config.json path if no environment variable is set.

**Comment by svetha-cvl** [comment]
I'd be happy to submit a PR if the idea is accepted.

**Comment by hsluoyz** [comment]
@svetha-cvl plz make a PR, thanks!
