### ISSUE TITLE
Casbin-Server multi deployment

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [apache/casbin-server#55]
Quick scenario:  
Imagine that I have a deployment of 2 Casbin-Servers behind a load balancer without sticky session. The client starts the flow by requesting a Adapter. This request gets balanced to server A. The next request, for an enforcer, will be balanced to server B, which will not have any idea about the Adapter and that will result in a error.

Correct?

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira yes, Casbin-Server is not stateless. You need to enable sticky session for multi-host deployment.

**Comment by Leonardo-Ferreira** [comment]
can I make it so? or at least, configurable?

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira Casbin is a memory-based policy enforcer, meaning the policy data will first be loaded into memory before they can be used for permission checking. Casbin-Server is originally designed as a container to hold only a portion of all the policy data. So if your total size of policy rules is larger than the memory size of a single machine, then better use sharding, see: https://casbin.org/docs/en/performance#high-number-of-policy-rules

**Comment by Leonardo-Ferreira** [comment]
> if your total size of policy rules is larger than the memory size of a single machine

I'm not even considering this right now. Im only considering that you should have a minimum redundant deploy in case your node crashes...

**Comment by Leonardo-Ferreira** [comment]
I'm also thinking: the client should not be able to directly request the creation of new adapters and enforcers. 

IMHO the adapters should be pre-configured (config file, env variables, database storage or elsewhere) and the server would manage the instantiation of the enforcers.  
The client would then query for a enforcer handle, passing as argument a scope/realm/appId (connection string is a too much of a sensitive info) and the server would return with the handle of the enforcer that matches the adapter of the scope/realm/appId.

Here's an example of proto:
```
rpc GetEnforcerHandle (EnforcerQueryRequest) returns (EnforcerHandleReply) {}

message EnforcerQueryRequest {
  string realm = 1;
}
```

**Comment by CaffreyZhang** [comment]
> > if your total size of policy rules is larger than the memory size of a single machine
> 
> I'm not even considering this right now. Im only considering that you should have a minimum redundant deploy in case your node crashes...

Hi, is there any progress on this issue now? I have also encountered this problem. The way I'm handling it is to deploy multiple nodes in a master-slave fashion and forward the traffic to the master node when the slave node receives it.

**Comment by hsluoyz** [comment]
Closed as stale
