### ISSUE TITLE
can you support AddPolicies action

### ISSUE THREAD

**Issue by zsk1993** [apache/casbin-server#63]
thanks

**Comment by zsk1993** [comment]
and the RemovePolicies() actions,thank you very much

**Comment by hsluoyz** [comment]
@Abingcbc @seriouszyx

**Comment by damirsharip** [comment]
What is the AddPolicies and RemovePolicies, where we should write it? a little bit unclear for me to contribute, 
thnx

**Comment by zsk1993** [comment]
> What is the AddPolicies and RemovePolicies, where we should write it? a little bit unclear for me to contribute, thnx
AddPolicies and RemovePolicies are functions of casbin, here is：https://casbin.org/docs/en/management-api#addpolicies
I had add the functions at the proto/casbin.proto and server/management_api.go,maybe i can contribute the code.

**Comment by zsk1993** [comment]
> > What is the AddPolicies and RemovePolicies, where we should write it? a little bit unclear for me to contribute, thnx
> > AddPolicies and RemovePolicies are actions of casbin, here is：https://casbin.org/docs/en/management-api#addpolicies
> > I had add the functions at the proto/casbin.proto and server/management_api.go,maybe i can contribute the
