### ISSUE TITLE
Concurrency issue in enforcer.go

### ISSUE THREAD

**Issue by nsarup** [apache/casbin-server#72]
1. We are load testing the server using k6 tool and when i try to load the server with multiple users it crashes.
2. The issue is that the maps used in enforcer.go (enforcerMap and adapterMap) need to be thread safe.
3. Use either a sync map OR a RWMutex and protect the code where map is being written into.
4. I was able to resolve it for myself using mutex, urge you to do the same.

**Comment by hsluoyz** [comment]
@JalinWang 

/cc @tangyang9464

**Comment by JalinWang** [comment]
@nsarup Thanks very much for your suggestion!
I've made a PR. Could you plz take a look? #73
