### ISSUE TITLE
CasBin server 1.02 can't be compiled for MSSQL

### ISSUE THREAD

**Issue by amoorthaemer** [apache/casbin-server#74]
Hi,

I wanted to try casbin server with MSSQL, but I found out that the repo: github.com/jinzhu/gorm/dialects/mssql doesn't exist anymore. 
So my question is: is or will MSSQL still be supported in casbin server?

TIA

Bert

**Comment by hsluoyz** [comment]
The latest gorm-adapter v3.14.0 already supports MSSQL now: https://github.com/casbin/gorm-adapter/releases/tag/v3.14.0

Need to update this repo to use gorm-adapter v3.14.0

**Comment by yyy1000** [comment]
> Hi,
> 
> I wanted to try casbin server with MSSQL, but I found out that the repo: github.com/jinzhu/gorm/dialects/mssql doesn't exist anymore. So my question is: is or will MSSQL still be supported in casbin server?
> 
> TIA
> 
> Bert

Hi, we have fixed this in the new version.
You could try it.
Thanks for your issue.
