### ISSUE TITLE
Publish each minor release to DockerHub

### ISSUE THREAD

**Issue by hsluoyz** [apache/casbin-server#76]
See: https://hub.docker.com/r/casbin/casbin-server/tags

Casbin-Server should use a similar way like Casdoor:

- https://github.com/casdoor/casdoor
- https://hub.docker.com/r/casbin/casdoor/tags

**Comment by zhenglin-charlie-li** [comment]
Interested in this!

I compared the Docker image at https://hub.docker.com/r/casbin/casbin-server/tags with the releases at https://github.com/casbin/casbin-server/releases. I found that the last docker image of casbin-server on Docker Hub was pushed one year ago, but the most recent release was published two weeks ago.

So, I would like to clarify: Is this issue about pushing a container image to Docker Hub when there is a release version?

**To accomplish this, I believe we could create a new YML file in.github/workflows. Then, when Github Action detects a new release, let Github Action trigger Docker push. Will that work?**
