### ISSUE TITLE
URL 404 

### ISSUE THREAD

**Issue by zhenglin-charlie-li** [apache/casbin-server#80]
The url here is 404; we should fix this as it is located on the main page and serves as an important guideline for our users.

![image](https://user-images.githubusercontent.com/63448884/210938154-6ee5ce0e-8ac2-4949-93e4-4d8712b5b8fb.png)

![image](https://user-images.githubusercontent.com/63448884/210938093-09480278-95db-4822-ba09-0d79848def94.png)

**Comment by nomeguy** [comment]
fixed: https://casbin.org/docs/service
