### ISSUE TITLE
How to run this docker image?

### ISSUE THREAD

**Issue by sibaiabis** [apache/casbin-server#82]
I downloaded the image you provided from the docker, but I don't know how to start it. Is it 'docker run -- name xxx - p 50051:50051 casbin/casbin-server'? Don't need to specify additional env variables?
Thanks.

**Comment by yyy1000** [comment]
Yeah, No need to specify additional env variables.
Make sure the port in your server matches that in your client.

**Comment by hsluoyz** [comment]
We need to add a Docker usage section in the README, tell people how to use Casbin-Server in Docker. Refer to: https://casdoor.org/docs/basic/try-with-docker , maybe not that long, but it needs to be there

**Comment by sibaiabis** [comment]
> We need to add a Docker usage section in the README, tell people how to use Casbin-Server in Docker. Refer to: https://casdoor.org/docs/basic/try-with-docker , maybe not that long, but it needs to be there


Can add the Kubernetes usage section in README too?
